spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/WineApplication?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19961017zqh
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.wines.pojo