package com.example.wines.pojo;


public class Location {
	protected Wines wineTitle;
	protected String country;
	protected String province;
	protected String regin1;
	protected String regin2;
	
	
	
	// This constructor can be used for reading records from MySQL, where we have all fields,
	// including the PostId.
	public Location(Wines wineTitle, String country, String province, String regin1,
			String regin2) {
		this.wineTitle = wineTitle;
		this.country = country;
		this.province = province;
		this.regin1 = regin1;
		this.regin2 = regin2;
	}

	public Location(){}
	
	// This constructor can be used for reading records from MySQL, where we only have the postId,
	// such as a foreign key reference to PostId.
	// Given PostId, we can fetch the full BlogPost record.
	public Location(Wines wineTitle) {
		this.wineTitle = wineTitle;
	}
	
	// This constructor can be used for creating new records, where the postId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Location(String country, String province, String regin1,
			String regin2) {
		this.country = country;
		this.province = province;
		this.regin1 = regin1;
		this.regin2 = regin2;
		
	}

	/**
	 * @return the wineTitle
	 */
	public Wines getWineTitle() {
		return wineTitle;
	}

	/**
	 * @param wineTitle the wineTitle to set
	 */
	public void setWineTitle(Wines wineTitle) {
		this.wineTitle = wineTitle;
	}

	/**
	 * @return the country
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * @param country the country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * @return the province
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * @param province the province to set
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * @return the regin1
	 */
	public String getRegin1() {
		return regin1;
	}

	/**
	 * @param regin1 the regin1 to set
	 */
	public void setRegin1(String regin1) {
		this.regin1 = regin1;
	}

	/**
	 * @return the regin2
	 */
	public String getRegin2() {
		return regin2;
	}

	/**
	 * @param regin2 the regin2 to set
	 */
	public void setRegin2(String regin2) {
		this.regin2 = regin2;
	}
	
}